#!/bin/bash
set -e
shopt -s nullglob


############################
# 時間計測開始
############################
TOTAL_START=$(date +%s)


echo "=== Pipeline started at $(date) ==="


############################################
# Part 0 : 設定
############################################
WORKDIR=/home/shimizu140816/data/individual
REFDIR=/home/shimizu140816/data/ref
REF=GCF_000180615.1_FUGU5_genomic.fna
CONTAINER=bioinfo
THREADS=4


############################################
# Part 1 : Trimming
############################################
echo "=== Part1: Trimming ==="
P1_START=$(date +%s)


mkdir -p "$WORKDIR/trimed" "$WORKDIR/trimlog"


for f1 in "$WORKDIR"/DRR*_1.fastq.gz; do
    base=$(basename "$f1" _1.fastq.gz)


    docker run --rm \
      -v "$WORKDIR":/data \
      -w /data \
      "$CONTAINER" \
      trimmomatic PE \
        -threads 8 \
        -phred33 \
        -trimlog "trimlog/${base}_trimlog.txt" \
        "${base}_1.fastq.gz" "${base}_2.fastq.gz" \
        "trimed/${base}_1.fastq.gz" "trimlog/${base}_unpaired_1.fastq.gz" \
        "trimed/${base}_2.fastq.gz" "trimlog/${base}_unpaired_2.fastq.gz" \
        ILLUMINACLIP:/usr/local/share/trimmomatic/TruSeq3-PE-2.fa:2:30:10 \
        LEADING:19 TRAILING:19 CROP:146 HEADCROP:5 SLIDINGWINDOW:30:20 \
        AVGQUAL:20 MINLEN:60
done


P1_END=$(date +%s)
P1_TIME=$((P1_END - P1_START))


############################################
# Part 2 : Index作成 + Mapping
############################################
echo "=== Part2: Index & Mapping ==="
if [ ! -f "$REFDIR/${REF%.fna}.dict" ]; then
  docker run --rm \
    -v "$REFDIR":/ref \
    -w /ref \
    "$CONTAINER" \
    bash -c "
      bwa index $REF && \
      samtools faidx $REF && \
      gatk --java-options '-Xmx32G -Xms32G' CreateSequenceDictionary -R $REF
    "
fi


MAPDIR="$WORKDIR/trimed"
OUTDIR="$MAPDIR/BAM"
mkdir -p "$OUTDIR"
for f1 in "$MAPDIR"/DRR*_1.fastq.gz; do
  base=$(basename "$f1" _1.fastq.gz)
  f2="$MAPDIR/${base}_2.fastq.gz"


  docker run --rm \
    -v "$REFDIR":/ref \
    -v "$MAPDIR":/work \
    -v "$OUTDIR":/bam \
    -w /work \
    "$CONTAINER" \
    bash -c "
      bwa mem -M -t $THREADS \
        -R '@RG\tID:$base\tSM:$base' \
        /ref/$REF \
        ${base}_1.fastq.gz ${base}_2.fastq.gz | \
      samtools view -Sb - > /bam/${base}.bam
    "
done


P2_END=$(date +%s)
P2_TIME=$((P2_END - P2_START))


############################################
# Part 3 : Sort & MQ filter
############################################
echo "=== Part3: Sort & MQ Filter ==="
P3_START=$(date +%s)


WORKBAM="$OUTDIR"
SORTED_DIR=${WORKBAM}/sorted_bam
MQ_DIR=${WORKBAM}/MQfiltered_bam


mkdir -p "$SORTED_DIR" "$MQ_DIR"


for bam in "$WORKBAM"/DRR*.bam; do
  base=$(basename "$bam" .bam)


  docker run --rm \
    -v "$WORKBAM":/bam \
    -v "$SORTED_DIR":/sorted \
    -v "$MQ_DIR":/mq \
    "$CONTAINER" \
    bash -c "
      samtools sort -@ $THREADS \
        -o /sorted/${base}_mem.sorted.bam \
        /bam/${base}.bam && \
      samtools index -@ $THREADS \
        /sorted/${base}_mem.sorted.bam && \
      samtools view -b -q 10 \
        /sorted/${base}_mem.sorted.bam \
        > /mq/${base}_mem.MQ10.bam && \
      samtools index -@ $THREADS \
        /mq/${base}_mem.MQ10.bam
    "
done


P3_END=$(date +%s)
P3_TIME=$((P3_END - P3_START))


############################################
# Part 4 : HaplotypeCaller
############################################
echo "=== Part4: HaplotypeCaller ==="
P4_START=$(date +%s)


for bam in "$MQ_DIR"/*.bam; do
  sample=$(basename "$bam" .MQ10.bam)


  docker run --rm \
    -v "$REFDIR":/ref \
    -v "$MQ_DIR":/mq \
    -w /mq \
    "$CONTAINER" \
    bash -c "
      gatk --java-options '-Xmx32G -Xms32G' HaplotypeCaller \
        -R /ref/$REF \
        -I ${sample}.MQ10.bam \
        -O ${sample}.g.vcf.gz \
        -ERC GVCF \
        --stand-call-conf 30
    "
done


P4_END=$(date +%s)
P4_TIME=$((P4_END - P4_START))


############################################
# 全体時間
############################################
TOTAL_END=$(date +%s)
TOTAL_TIME=$((TOTAL_END - TOTAL_START))


############################################
# 時間表示
############################################
echo ""
echo "========= TIME SUMMARY ========="
printf "Part1 (Trimming):        %02d:%02d:%02d\n" $((P1_TIME/3600)) $((P1_TIME%3600/60)) $((P1_TIME%60))
printf "Part2 (Index+Mapping):   %02d:%02d:%02d\n" $((P2_TIME/3600)) $((P2_TIME%3600/60)) $((P2_TIME%60))
printf "Part3 (Sort+MQ):         %02d:%02d:%02d\n" $((P3_TIME/3600)) $((P3_TIME%3600/60)) $((P3_TIME%60))
printf "Part4 (HaplotypeCaller): %02d:%02d:%02d\n" $((P4_TIME/3600)) $((P4_TIME%3600/60)) $((P4_TIME%60))
printf "TOTAL TIME:              %02d:%02d:%02d\n" $((TOTAL_TIME/3600)) $((TOTAL_TIME%3600/60)) $((TOTAL_TIME%60))
echo "================================"




